name: Continuous Integration/ Continuous Deployment
on:
  pull_request:
    types:
      - opened
    branches:
      - dev
      - staging      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Node LTS versions
      uses: msimerson/node-lts-versions@v1.1.1
    - run: npm install --force
    - name: Run test scripts
      run: npm test --ci --coverage
    - uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 80
          package-manager: npm
          test-script: npm run test:cov

            #- name: SonarCloud Scan
            #uses: sonarsource/sonarcloud-github-action@master
            #env:
            #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
